image: docker:git

stages:
  - build
 
.docker:
  image: docker:git
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""

build_only:
  extends: .docker
  stage: build
  except:
    - master
  script:  
    - docker build --no-cache -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:php7 php7
  
build_deploy:
  extends: .docker
  stage: build
  only:
    - master
  script:  
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --no-cache -t $CI_REGISTRY/$CI_PROJECT_PATH:latest .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:php7 php7
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:php7
    